openapi: 3.0.3
info:
  title: Student API
  description: Student API for managing students
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: local server
paths:
  /students:
    get:
      operationId: getStudents
      summary: Get all students
      description: Get all students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponse'
        '404':
            description: No students found
            content:
                application/json:
                    schema:
                      $ref: '#/components/schemas/ApiResponse'
                    example:
                      code: 404
                      message: No students found
        '500':
            description: Internal server error
            content:
                application/json:
                    schema:
                      $ref: '#/components/schemas/ApiResponse'
                    example:
                      code: 500
                      message: Internal server error
components:
    schemas:
        Student:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            age:
              type: integer
              format: int32
            grade:
              type: string
        ApiResponse:
          type: object
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
            data:
              type: array
              items:
                $ref: '#/components/schemas/Student'